on:
  workflow_call:
    outputs:
      image_tag:
        description: "Docker image tag"
        value: ${{ jobs.build.outputs.image_tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.tag.outputs.tag }}
    steps:
      - id: tag
        run: echo "tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT


        name: Build Docker Image
