---
name: Release Docker Image

on:
  workflow_dispatch:
  release:
    types: [published]
  workflow_run:
    workflows:
      - Build Docker Image
    types:
      - completed

env:
  IMAGE_NAME: mortcal
  RG_STG: mortcal-rg-stg
  ACA_APP_STG: mortcal-containerapp-stg
  RG_PROD: mortcal-rg-prod
  ACA_APP_PROD: mortcal-containerapp-prod

jobs:
  deploy-stg:
    name: Deploy to STG ACA
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download Image Tag
        uses: actions/download-artifact@v4
        with:
          name: image-tag
          run-id: ${{ github.event.workflow_run.id }}

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=$(cat image-tag.txt)" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to ACA (STG)
        run: |
          az containerapp update \
            --name $ACA_APP_STG \
            --resource-group $RG_STG \
            --image tiggy081/$IMAGE_NAME:$IMAGE_TAG

  deploy-prod:
    name: Deploy to PROD ACA
    runs-on: ubuntu-latest
    needs: deploy-stg
    environment: prod  # GitHub will enforce manual approval
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Download Image Tag
        uses: actions/download-artifact@v4
        with:
          name: image-tag

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=$(cat image-tag.txt)" >> $GITHUB_ENV

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to ACA (PROD)
        run: |
          az containerapp update \
            --name $ACA_APP_PROD \
            --resource-group $RG_PROD \
            --image tiggy081/$IMAGE_NAME:$IMAGE_TAG
